// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoESvUmThWZkmTiTXB-0B3F03cvkVt8Fg',
    appId: '1:799981142269:android:602d587eee1ad3d32efe94',
    messagingSenderId: '799981142269',
    projectId: 'oneklass-v2',
    storageBucket: 'oneklass-v2.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnfxafrhldM97OuKb6IDy_RDMMXDd3GxA',
    appId: '1:799981142269:web:0350787cbe96661d2efe94',
    messagingSenderId: '799981142269',
    projectId: 'oneklass-v2',
    authDomain: 'oneklass-v2.firebaseapp.com',
    storageBucket: 'oneklass-v2.appspot.com',
    measurementId: 'G-Q339MKL701',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNrRjkbJJtJxbWURBnXNCioGyd2rqhHAI',
    appId: '1:799981142269:ios:d694932b462d15ad2efe94',
    messagingSenderId: '799981142269',
    projectId: 'oneklass-v2',
    storageBucket: 'oneklass-v2.appspot.com',
    iosBundleId: 'com.example.oneKlass',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNrRjkbJJtJxbWURBnXNCioGyd2rqhHAI',
    appId: '1:799981142269:ios:d694932b462d15ad2efe94',
    messagingSenderId: '799981142269',
    projectId: 'oneklass-v2',
    storageBucket: 'oneklass-v2.appspot.com',
    iosBundleId: 'com.example.oneKlass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnfxafrhldM97OuKb6IDy_RDMMXDd3GxA',
    appId: '1:799981142269:web:df354c07dd57b4002efe94',
    messagingSenderId: '799981142269',
    projectId: 'oneklass-v2',
    authDomain: 'oneklass-v2.firebaseapp.com',
    storageBucket: 'oneklass-v2.appspot.com',
    measurementId: 'G-Q9G9Z8EFWS',
  );

}